[package]
name = "vamp-ir"
version = "0.1.3"
edition = "2021"

[lib]
name = "vamp_ir"
path = "src/lib.rs"
bench = false

[features]
# Enable Standard Library
std = []

[dependencies]
pest = "2.0"
pest_derive = "2.0"
ark-ff = "0.3"
ark-ec = "0.3"
ark-bls12-381 = "0.3"
ark-ed-on-bls12-381 = "0.3"
ark-poly = "0.3"
ark-poly-commit = "0.3"
ark-serialize = "0.3.0"
clap = { version = "4.0.17", features = [ "derive" ] }
group = "0.13"
halo2_proofs = "0.3.0"
halo2_gadgets = "0.3.0"
ff = "0.13"
num-bigint = "^0.4.0"
num-traits = "^0.2.14"
bincode = "2.0.0-rc.1"
rand_core = "0.6.3"
plonk = { git = "https://github.com/ZK-Garage/plonk", rev = "ec76fd36cc6b9e9d0f7a9495094e76b86e53dab4" }
plonk-core = { git = "https://github.com/ZK-Garage/plonk", rev = "ec76fd36cc6b9e9d0f7a9495094e76b86e53dab4", features = [ "std", "trace", "trace-print" ] }
serde_json = "1.0.93"

[[bench]]
name = "plonk_benches"
harness = false

[[bench]]
name = "halo2_benches"
harness = false


[dev-dependencies]
criterion = "0.3"
proptest = "1.0.0"

[target.'cfg(unix)'.dev-dependencies]
inferno = ">=0.11, <0.11.5" # MSRV 1.59
pprof = { version = "0.8", features = ["criterion", "flamegraph"] } # MSRV 1.56

[build]
rustflags = ["-Clinker=rust-lld"]